### ISSUE TITLE
Coverage for African languages

### ISSUE THREAD

**Issue by dohliam** [6/stopwords-json#4]
Great project! I noticed there are currently no African languages included, so I've started the [more-stoplists](https://github.com/dohliam/more-stoplists) project to rectify that.

We are in the process of creating approximately 50-60 lists of stopwords from the [ASP corpus](https://github.com/global-asp/asp-source). Swahili and Afrikaans are already complete, and the rest will follow gradually as we go through the process of manually checking each of the automatically generated lists.

Would it be okay if I submitted a PR with the extra languages? In commit 900b3fa5 I have added `af.json` and `sw.json`, and updated the `stopwords-all.json` and `README.md` files. I could start with these and submit the others as they are completed. Let me know what you think!

**Comment by 6** [comment]
Looks great! Yes, please feel free to submit a PR with additional languages, I would be happy to review.

**Comment by dohliam** [comment]
Great to see that this project is still active! I've submitted a PR for 7 new languages from the corpus. Some background on the corpus and the methodology can be found in [this repo](https://github.com/dohliam/more-stoplists), where we are working on creating more lists of stopwords. I can submit further pull requests as the new languages are completed.

**Comment by 6** [comment]
https://github.com/6/stopwords-json/pull/8
