### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by oncletom** [6/stopwords-json#5]
Hello,

thanks for this very handy repo.
Is there any chance you to publish on npm?

The only problem I see is the name collision as someome already employ this package name.
But I guess `@6/stopwords` would work.

What do you think?

**Comment by 6** [comment]
good suggestion 👍 , done! https://www.npmjs.com/package/stopwords-json

it's also on bower now too

**Comment by oncletom** [comment]
Brilliant thanks :-)
